### ISSUE TITLE
Resize the Fees receipt print

### ISSUE THREAD

**Issue by vidyanair86** [blocksbuilder/strocks-webapp-issue-tracker#6]
**Describe the bug
**reduce the size of receipt print.  Half of the A4 size or if it is possible to reduce more than half of A4 **

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blocksbuilder** [comment]
this is done

**Comment by blocksbuilder** [comment]
latest changes are available now
